# This is a basic workflow to help you get started with Actions

name: Deploy to Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags: [ "v*.*.*" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  zip-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: release
        uses: elgohr/Github-Release-Action@v4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: "TBX-Basic_dialect"
          tag_name: ${{ github.ref_name }}


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          zip -r TBX-Basic_dialect_${{ github.ref_name }}.zip ./*

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./TBX-Basic_dialect_${{ github.ref_name }}.zip
          asset_name: TBX-Basic_dialect_${{ github.ref_name }}.zip
          asset_content_type: application/zip
        
